### PR TITLE
Issue #85: Rendering highlights becomes painfully slow for longer documents

### PR DESCRIPTION
**Pull request by reckart**
- Use `createNodeIterator` to fetch a fast iterator over only the text nodes to speed things up

### CODE REVIEW

**Comment by rsimon** [comment]
This is excellent - and indeed has been bothering me since long ago, too. Do you have a rough estimate how much that change has improved performance?

**Comment by reckart** [comment]
I'd say for one document I'm presently looking at from several seconds down to milliseconds.

**Comment by reckart** [comment]
There was a small bug in the PR that a last node partially included in the maxOffset was not in the result. That should be fixed now as well.

**Comment by rsimon** [comment]
Wow - fantastic. I'm just testing it, and there seems to be an issue when using relations. (In the default test HTML page, there are three highlights plus one relation.) Could be a race condition of some kind... I'm travelling right now, but will try to debug later.

**Comment by reckart** [comment]
Before the patch, my users were complaining about a noticeable delay when scrolling further down in the document - which is now not noticeable anymore.

Could it be that the connections plugin may have problems with recogito due to recogito JS rendering stuff in async batches instead of all in one go which might cause the connections to kick in before all of the highlights are rendered?

**Comment by rsimon** [comment]
Wait - your last commit did the trick it seems. Works now!

**Pull request merged**
